language: php
dist: bionic
php:
  - 7.4
before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y apache2
  - sudo apt-get install -y  php
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-get install composer
  - sudo service apache2 restart
  - npm install lodash
  - npm install puppeteer
  - npm install @nesk/rialto
  - composer update

script: 
  - ./vendor/bin/phpunit --verbose tests 
