language: php
dist: xenial
php:
  - 7.2
before_install:
  - sudo apt-get -y update

install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt --fix-broken  install ./google-chrome-stable_current_amd64.deb
