language: php
dist: xenial
php:
  - 7.2
before_install:
  - sudo apt-get -y update
  - sudo apt install unzip
  - sudo apt install nodejs
  - composer install
  - composer update
  - npm install @nesk/puphpeteer
  - composer require nesk/puphpeteer
  - composer dump-autoload
install:
  - nohup php -S localhost:9000 -t src/ > phpd.log  2>&1 &
script: phpunit tests