language: php
dist: xenial
php:
  - 7.2
before_install:
  - sudo apt-get -y update
  - sudo apt install unzip
  - composer install
install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt --fix-broken  install ./google-chrome-stable_current_amd64.deb
  - wget https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - nohup php -S localhost:9000 -t src/ > phpd.log  2>&1 &
script: phpunit tests